<a href="https://colab.research.google.com/github/RaoSaeed836/100_Day_ML/blob/main/Column_Transformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np
import pandas as pd

In [19]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import LabelEncoder


In [20]:
df=pd.read_csv("/content/covid_toy.csv")
df

age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [21]:
x=df.drop(columns=['has_covid'])
y=df['has_covid']

In [22]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=56)

In [23]:
from sklearn.compose import ColumnTransformer

In [27]:
transformer=ColumnTransformer(transformers=[
('tf1',SimpleImputer(),['fever']), # Corrected column name from 'Fever' to 'fever'
('tf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']), # Corrected column name from 'Cough' to 'cough'
('tf3',OneHotEncoder(drop='first',dtype=np.int32),['gender','city']) # Corrected column names and dtype
],remainder='passthrough')

In [28]:
transformer.fit_transform(X_train)

array([[104.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  17.        ],
       [100.66197183,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  84.        ],
       [102.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  49.        ],
       [100.66197183,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  71.        ],
       [ 99.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  72.        ],
       [100.66197183,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  20.        ],
       [102.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   5.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  19.        ],
       [104.        ,   0.        ,   0.        ,   0.        ,
          0.    

In [29]:
transformer.transform(X_test)

array([[102.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  82.        ],
       [103.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  48.        ],
       [ 98.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  80.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  54.        ],
       [100.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  47.        ],
       [101.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  49.        ],
       [ 98.        ,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  34.        ],
       [101.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  64.        ],
       [104.        ,   0.        ,   0.        ,   0.        ,
          1.    

###Practice column transfomer


survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [42]:
df=df[['who','embarked','class','embark_town','age','deck']]
df

who embarked   class  embark_town   age deck
0      man        S   Third  Southampton  22.0  NaN
1    woman        C   First    Cherbourg  38.0    C
2    woman        S   Third  Southampton  26.0  NaN
3    woman        S   First  Southampton  35.0    C
4      man        S   Third  Southampton  35.0  NaN
..     ...      ...     ...          ...   ...  ...
886    man        S  Second  Southampton  27.0  NaN
887  woman        S   First  Southampton  19.0    B
888  woman        S   Third  Southampton   NaN  NaN
889    man        C   First    Cherbourg  26.0    C
890    man        Q   Third   Queenstown  32.0  NaN

[891 rows x 6 columns]

In [48]:
df=df.drop(columns=['deck'])


KeyError: "['deck'] not found in axis"

In [59]:
x=df.iloc[:,1:]
y=df['who']
x

embarked   class  embark_town   age
0          S   Third  Southampton  22.0
1          C   First    Cherbourg  38.0
2          S   Third  Southampton  26.0
3          S   First  Southampton  35.0
4          S   Third  Southampton  35.0
..       ...     ...          ...   ...
886        S  Second  Southampton  27.0
887        S   First  Southampton  19.0
888        S   Third  Southampton   NaN
889        C   First    Cherbourg  26.0
890        Q   Third   Queenstown  32.0

[891 rows x 4 columns]

In [60]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=67)

In [65]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

In [72]:
transformer=ColumnTransformer(transformers=[
    ('tf1',OrdinalEncoder(categories=[['First','Second','Third']]),['class']),
    ('tf2',SimpleImputer(),['age']),
    ('tf3',OneHotEncoder(dtype=np.int32,drop='first'),['embarked','embark_town'])
],remainder='passthrough')

In [73]:
transformer.fit_transform(X_train)

array([[ 2., 47.,  0., ...,  0.,  1.,  0.],
       [ 2., 23.,  0., ...,  0.,  1.,  0.],
       [ 2., 29.,  0., ...,  0.,  1.,  0.],
       ...,
       [ 1., 52.,  0., ...,  0.,  1.,  0.],
       [ 2., 27.,  0., ...,  0.,  1.,  0.],
       [ 0., 39.,  0., ...,  0.,  0.,  0.]])

In [74]:
transformer.transform(X_test)

array([[ 1.        , 52.        ,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       [ 2.        , 29.62508108,  1.        , ...,  1.        ,
         0.        ,  0.        ],
       [ 0.        , 51.        ,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [ 2.        , 30.        ,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       [ 1.        , 41.        ,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       [ 2.        , 38.        ,  0.        , ...,  0.        ,
         1.        ,  0.        ]])